# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-KakakuCom
version:      0.05
version_from: lib/WebService/KakakuCom.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    Class::Data::Inheritable:      0
    Data::Page:                    0
    Jcode:                         0
    LWP::UserAgent:                0
    Readonly:                      0
    Test::More:                    0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
